### ISSUE TITLE
Unable to show blog posts in homepage.

### ISSUE THREAD

**Issue by craigary** [itsmingjie/ganymede#17]
Hi, huge fan of this theme but currently there's no article lists in homepage after activate the theme. It's suitable for your website (I love it) but personally I prefer to display all the posts on the first page😂😂😂, is there anyway to do it?

It would be nice if ganymede can use article lists as the default page, then use route.yaml to define which page shows on home page.

**Comment by roniardev** [comment]
same here ... ;,(

**Comment by roniardev** [comment]
solved with replace home.hbs code same as index.hbs

**Comment by roniardev** [comment]
[**@craigary** ](https://github.com/craigary) **this theme is use custom routes and custom home page, i understand after read this doc** https://ghost.org/tutorials/custom-home-page/

**Comment by craigary** [comment]
@roniardynt Thank you and I'll take a look, I thought it use route.yaml to set custom homepage but obviously its not. So I was kinda confused 😂

**Comment by roniardynt** [comment]
@craigary  you must modify index.hbs to fix displaying page for hompage. my index.hbs is like this  
 

```handlebars
{{!< default}}
{{!-- The tag above means: insert everything in this file
into the {body} of the default.hbs template --}}
{{> header}}

{{!-- Everything inside the #post tags pulls data from the post --}}
{{#page}}

<main class="main_minimal" role="main">
   <article class="article__wrapper" role="article">
       <header>
           <h1 class="post__title">{{title}}</h1>
       </header>

       <section class="post__content-wrapper">
           <div class="post__content">
               {{content}}
           </div>
       </section>
   </article>
</main>

{{/page}}
```

first time trying i'm kinda confused too, but i modified home.hbs and its work.

**Comment by roniardev** [comment]
@craigary  you must modify home.hbs to fix displaying page for hompage. my home.hbs is like this  
 

```handlebars
{{!< default}}
{{!-- The tag above means: insert everything in this file
into the {body} of the default.hbs template --}}
{{> header}}

{{!-- Everything inside the #post tags pulls data from the post --}}
{{#page}}

<main class="main_minimal" role="main">
   <article class="article__wrapper" role="article">
       <header>
           <h1 class="post__title">{{title}}</h1>
       </header>

       <section class="post__content-wrapper">
           <div class="post__content">
               {{content}}
           </div>
       </section>
   </article>
</main>

{{/page}}
```

first time trying i'm kinda confused too, but i modified home.hbs and its work.

**Comment by itsmingjie** [comment]
Yup -- sorry about this. I changed the homepage into a custom page. You can change it back by following @roniardynt's solution above. Closing for now.
